jid: git@localhost/agent
password: testing
debug: true
jabber_debug: true
log_path: :error
pid_path: tmp/git.pid
actor_path: actors
herault_jid: herault@localhost/herault
actor_path: lib
actors:
 - vertebra_git/actors/watcher
